# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compendia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prescribed_Medicines',
            new_name='PrescribedMedicine',
        ),
    ]
