# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compendia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='join_date_doc',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of joining'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='join_date_hosp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of joining'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of joining'),
        ),
    ]
